- name: create etcd service for systemctl
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644

- name: Just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Enable service httpd and ensure it is not masked
  systemd:
    name: etcd
    state: started
    enabled: yes
    masked: no